# Site settings
title: Raphael Waldemar
description: Hub Links
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raphael Waldemar
user_description: Desde a graduação em Engenharia Elétrica pela UFMT, sempre fui movido pela curiosidade de entender como as coisas funcionam — e, principalmente, como podem funcionar melhor. Logo no início da minha carreira, ainda como estagiário na Eletronorte, descobri o impacto real que processos bem estruturados têm no dia a dia das equipes. Essa visão me acompanhou quando ingressei na ATIVA, onde comecei como Analista de Suporte mergulhando em integração de soluções, atendimento ao cliente e melhoria contínua. Com o tempo, evoluí para Coordenador de Projetos, ampliando minha atuação em governança, métricas, padrões e eficiência operacional. A combinação da prática com formações como o MBA em Gerenciamento de Projetos, a pós-graduação em Engenharia de Produção e certificações como Green Belt consolidou minha paixão por gestão. Esse caminho natural me levou ao desafio de atuar como Gerente de PMO, liderando pessoas, estruturando processos, desenvolvendo equipes e transformando estratégias em resultados reais. Minha trajetória segue sendo, acima de tudo, sobre evoluir, aprender e ajudar times a entregarem seu melhor.
user_title: Engenheiro | Gestão de Projetos
email: raphaelwdrf@gmail.com

exclude: ['package.json', 'src', 'node_modules', 'vendor']

